server:
  port: 8087
  servlet:
    context-path: /notification

spring:
  application:
    name: notification-service

brevo:
  api-key: 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
  sender-email: hoangtunqs134@gmail.com
  sender-name: T Cinema

logging:
  level:
    your.package.EmailClient: DEBUG
    feign: DEBUG
