server:
  port: 8086
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://ep-jolly-meadow-a12tbdro.ap-southeast-1.aws.neon.tech/booking-service?sslmode=require
    username: neondb_owner
    password: npg_oAz8IGRuOpt0
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
    booking-service: http://localhost:8085/booking
    cinema-service: http://localhost:8084/cinema


payment:
  vnpay:
    tmn-code: 4I4FEVKE
    secret-key: XQ8LNANJO4K2QBW8SX005JOB8ZBVCX6U
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:4200/payment-result
    timeout: 15 # in minutes