server:
  port: 8083
  servlet:
    context-path: /movie

spring:
  application:
    name: movie-service
  datasource:
    url: "jdbc:postgresql://cdw-ticket-authentication-service-hoangtunqs134-03ce.c.aivencloud.com:14840/movie-service?sslmode=require"
    username: avnadmin
    password: AVNS_p3IPiJOXS_p0fAofory
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true