server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:postgresql://ep-jolly-meadow-a12tbdro.ap-southeast-1.aws.neon.tech/profile-service?sslmode=require
    username: neondb_owner
    password: npg_oAz8IGRuOpt0
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
