server:
  port: 8080
  servlet:
    context-path: /authentication

spring:
  application:
    name: authentication-service
  datasource:
    url: "jdbc:postgresql://cdw-ticket-authentication-service-hoangtunqs134-03ce.c.aivencloud.com:14840/authentication-service?sslmode=require"
    username: avnadmin
    password: AVNS_p3IPiJOXS_p0fAofory
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  api-docs:
    enabled: true
    path: /v1/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operations-sorter: method

openapi:
  service:
    api-docs: authentication-service
    server: http://localhost:8080/authentication
    title: Authentication Service
    version: 1.0.0

app:
  init-data: true
  admin-info:
    username: admin
    password: admin
    email: admin123@gmail.com
  services:
    profile: http://localhost:8081/profile

jwt:
  secret-key: 3c03248c00967ffebb8cee416bd0382d130da0b0cc3015ea149e40536fb80de1
  access-expiration: 24
  refresh-expiration: 168

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.springframework.http.converter: TRACE
#    com.fasterxml.jackson.databind: DEBUG