server:
  port: 8080
  servlet:
    context-path: /authentication

spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresql://dpg-cvl0j7c9c44c73f970jg-a.singapore-postgres.render.com:5432/authentication_yyed
    username: root
    password: oTQIUKUbZ5zwQDT3IX18xvjNP6A3AfcU
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true        # B?t API Docs
    path: /v1/api-docs      # ???ng d?n c?a API Docs (M?c ??nh: /v3/api-docs)
  swagger-ui:
    enabled: true        # B?t Swagger UI
    path: /swagger-ui    # ???ng d?n giao di?n Swagger
    operations-sorter: method # S?p x?p API

openapi:
  service:
    api-docs: authentication-service
    server: http://localhost:8080/authentication
    title: Authentication Service
    version: 1.0.0

app:
  init-data: true
  admin-info:
    username: admin
    password: admin
    email: admin123@gmail.com

jwt:
  secret-key: 3c03248c00967ffebb8cee416bd0382d130da0b0cc3015ea149e40536fb80de1
  access-expiration: 24
  refresh-expiration: 168

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    org.hibernate.SQL: DEBUG
#    org.springframework.http.converter: TRACE
#    com.fasterxml.jackson.databind: DEBUG