server:
  port: 8888

app:
  api-prefix: /api/v1

services:
  auth: http://localhost:8080/authentication
  user: http://localhost:8081

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/authentication/**
          filters:
            - StripPrefix=2

        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2

        - id: movie-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/movie/**
          filters:
            - StripPrefix=2

        - id: showtime-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/showtime/**
          filters:
            - StripPrefix=2

        - id: cinema-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/cinema/**
          filters:
            - StripPrefix=2

        - id: booking-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/booking/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
